import '@fortawesome/fontawesome-free/css/all.min.css'
import 'bootstrap-css-only/css/bootstrap.min.css'
import 'mdbreact/dist/css/mdb.css'
import Head from 'next/head'
import Image from 'next/image'
import CarouselPage from '../Component/Carousel'
import Gallery from '../Component/Gallery'

export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <CarouselPage />
        <Gallery />
      </main>
    </div>
  )
}
